[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["synapse_wrapped"]

[tool.setuptools.package-data]
synapse_wrapped = ["*.html", "*.css"]

